# Generated by Django 4.1.7 on 2023-03-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='activite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projet.elementdevis'),
        ),
    ]
